var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":232,"id":2908,"methods":[{"el":44,"sc":5,"sl":42},{"el":92,"sc":5,"sl":86},{"el":110,"sc":5,"sl":101},{"el":124,"sc":5,"sl":118},{"el":138,"sc":5,"sl":132},{"el":153,"sc":5,"sl":145},{"el":169,"sc":5,"sl":164},{"el":181,"sc":5,"sl":177},{"el":193,"sc":5,"sl":189},{"el":218,"sc":5,"sl":204},{"el":231,"sc":5,"sl":227}],"name":"PitclipseUiUtils","sl":40},{"el":49,"id":2909,"methods":[],"name":"PitclipseUiUtils.RunnableWithException","sl":47},{"el":54,"id":2909,"methods":[],"name":"PitclipseUiUtils.RunnableWithCoreException","sl":52},{"el":59,"id":2909,"methods":[],"name":"PitclipseUiUtils.ProviderWithCoreException","sl":57},{"el":64,"id":2909,"methods":[],"name":"PitclipseUiUtils.PredicateWithCoreException","sl":62},{"el":69,"id":2909,"methods":[],"name":"PitclipseUiUtils.RunnableWithCoreExceptionInterruptable","sl":67},{"el":77,"id":2909,"methods":[{"el":76,"sc":9,"sl":74}],"name":"PitclipseUiUtils.MissingViewException","sl":71}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
